version: "3.8"

services:
  mysql:
    image: mysql:8.4.7
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: Abc@12345
      MYSQL_USER: xampp
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3306:3306"
    networks:
      - xampp

networks:
  xampp:
    driver: bridge
